name: flutter_icediary_appauth
description: Demonstrates how to use the flutter_appauth plugin for icediary.
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_appauth: 2.2.0
  http: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
